# Generated by Django 6.0 on 2026-03-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0004_alter_task_executor_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(to='labels.label'),
        ),
    ]
